# Generated by Django 5.2.8 on 2025-11-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_buster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_overline', models.CharField(default='Lifewire-inspired', max_length=120)),
                ('hero_heading', models.CharField(default='Smart guides for the tech you actually use.', max_length=200)),
                ('hero_subheading', models.CharField(default='Reviews, explainers, and troubleshooting tips crafted with the same editorial polish you love on Lifewire.', max_length=280)),
                ('hero_primary_cta_label', models.CharField(default='Browse articles', max_length=50)),
                ('hero_secondary_cta_label', models.CharField(default='Latest drops', max_length=50)),
                ('newsletter_overline', models.CharField(default='Inbox utility', max_length=120)),
                ('newsletter_heading', models.CharField(default='Weekly digest with zero fluff.', max_length=180)),
                ('newsletter_body', models.CharField(default='Get Lifewire-inspired explainers and buying advice each Monday. We only send the good stuff.', max_length=280)),
                ('newsletter_cta_label', models.CharField(default='Subscribe', max_length=80)),
                ('newsletter_disclaimer', models.CharField(default='No spam. Unsubscribe anytime.', max_length=160)),
            ],
            options={
                'verbose_name': 'Homepage Settings',
            },
        ),
        migrations.CreateModel(
            name='QuickTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=280)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
