# Generated by Django 5.2.8 on 2025-11-24 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_buster', '0002_homepagesettings_quicktip'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowToSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('intro', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_time', models.CharField(blank=True, max_length=80)),
                ('prerequisites', models.TextField(blank=True, help_text='One item per line')),
                ('published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('summary', models.TextField()),
                ('verdict', models.CharField(max_length=200)),
                ('affiliate_url', models.URLField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('overall_score', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('pros', models.TextField(help_text='One per line')),
                ('cons', models.TextField(help_text='One per line')),
                ('why_trust_us', models.TextField(blank=True)),
                ('methodology', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyingGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('summary', models.TextField()),
                ('hero_quote', models.CharField(blank=True, max_length=200)),
                ('published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buying_guides', to='blog_buster.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuidePick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('verdict', models.CharField(help_text='e.g. Best Overall, Best Budget', max_length=80)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('pros', models.TextField(help_text='One item per line')),
                ('cons', models.TextField(help_text='One item per line')),
                ('price_range', models.CharField(blank=True, max_length=80)),
                ('affiliate_url', models.URLField(blank=True)),
                ('rating', models.PositiveIntegerField(default=4, help_text='1-5 scale')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('buying_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='blog_buster.buyingguide')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HowToStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('instructions', models.TextField()),
                ('tip', models.CharField(blank=True, max_length=200)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='blog_buster.howtoseries')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='ReviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('score', models.DecimalField(decimal_places=1, help_text='0-10 scale', max_digits=3)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='blog_buster.productreview')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
