# Generated by Django 5.2.8 on 2025-11-24 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_buster', '0003_howtoseries_productreview_buyingguide_guidepick_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('popular_posts', 'Popular Posts'), ('related_posts', 'Related Posts'), ('author_bio', 'Author Bio'), ('social_share', 'Social Share'), ('newsletter', 'Newsletter Signup'), ('categories', 'Categories'), ('recent_posts', 'Recent Posts'), ('quick_tips', 'Quick Tips'), ('buying_guides', 'Buying Guides')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelatedPostsWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_count', models.PositiveIntegerField(default=5)),
                ('show_by_category', models.BooleanField(default=True)),
                ('show_by_tags', models.BooleanField(default=True)),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_posts_config', to='blog_buster.sidebarwidget')),
            ],
        ),
        migrations.CreateModel(
            name='RecentPostsWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_count', models.PositiveIntegerField(default=5)),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recent_posts_config', to='blog_buster.sidebarwidget')),
            ],
        ),
        migrations.CreateModel(
            name='QuickTipsWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_count', models.PositiveIntegerField(default=3)),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quick_tips_config', to='blog_buster.sidebarwidget')),
            ],
        ),
        migrations.CreateModel(
            name='PopularPostsWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_count', models.PositiveIntegerField(default=5, help_text='Number of posts to display')),
                ('time_period_days', models.PositiveIntegerField(default=30, help_text='Show posts from last N days')),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popular_posts_config', to='blog_buster.sidebarwidget')),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Get the latest tech news and tutorials delivered to your inbox.')),
                ('button_text', models.CharField(default='Subscribe Now', max_length=50)),
                ('privacy_text', models.CharField(default='We respect your privacy.', max_length=200)),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_config', to='blog_buster.sidebarwidget')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_post_count', models.BooleanField(default=True)),
                ('max_categories', models.PositiveIntegerField(default=10)),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='categories_config', to='blog_buster.sidebarwidget')),
            ],
        ),
        migrations.CreateModel(
            name='BuyingGuidesWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_count', models.PositiveIntegerField(default=3)),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buying_guides_config', to='blog_buster.sidebarwidget')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorBioWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_text', models.TextField(help_text='Author biography text')),
                ('show_social_links', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='author_avatars/')),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_bio_config', to='blog_buster.sidebarwidget')),
            ],
        ),
        migrations.CreateModel(
            name='SocialShareWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_facebook', models.BooleanField(default=True)),
                ('show_twitter', models.BooleanField(default=True)),
                ('show_linkedin', models.BooleanField(default=True)),
                ('show_pinterest', models.BooleanField(default=True)),
                ('show_email', models.BooleanField(default=True)),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_share_config', to='blog_buster.sidebarwidget')),
            ],
        ),
    ]
